# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_attendanceregularization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceregularization',
            name='cc',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
