# Generated by Django 6.0.5 on 2026-06-28 06:06

from django.db import migrations, models
from django.utils.text import slugify


def forwards(apps, schema_editor):
    JobOpening = apps.get_model('people', 'JobOpening')
    Candidate = apps.get_model('people', 'Candidate')
    status_map = {
        'screening': 'shortlisted',
        'interview': 'interview_scheduled',
        'offer': 'selected',
        'hired': 'selected',
    }
    for candidate in Candidate.objects.all():
        if candidate.status in status_map:
            candidate.status = status_map[candidate.status]
            candidate.save(update_fields=['status'])

    for job in JobOpening.objects.all():
        if job.public_slug:
            continue
        base = slugify(job.title)[:150] or f'job-{job.pk}'
        slug = base
        counter = 1
        while JobOpening.objects.filter(public_slug=slug).exclude(pk=job.pk).exists():
            slug = f'{base}-{counter}'
            counter += 1
        job.public_slug = slug
        job.save(update_fields=['public_slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_leavetype_shift_department_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=24),
        ),
        migrations.AlterField(
            model_name='exitrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
