from django.urls import path

from .views import (
    AdminAttendanceApiView,
    AdminDashboardStatsView,
    AdminDashboardView,
    AdminEmployeeDetailApiView,
    AdminEmployeeLocationApiView,
    AdminEmployeesApiView,
    AdminHelpdeskStatusApiView,
    AdminLeaveStatusApiView,
    AdminTasksApiView,
    AdminRegularizationStatusApiView,
    AttendanceReportView,
    CheckInView,
    CheckOutView,
    EmployeeAttendanceRegularizationView,
    EmployeeDirectoryView,
    EmployeeHelpdeskTicketsView,
    EmployeeLeaveRequestsView,
    EmployeePayslipPdfView,
    EmployeeSalaryView,
    EmployeeTasksView,
    MeView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    PasswordResetVerifyView,
    UserDashboardView,
    admin_dashboard_panel,
    update_leave_request_status,
    update_regularization_status,
)


urlpatterns = [
    path('admin-panel/', admin_dashboard_panel, name='admin-dashboard-panel'),
    path(
        'admin-panel/leaves/<int:leave_id>/<str:new_status>/',
        update_leave_request_status,
        name='admin-leave-status',
    ),
    path(
        'admin-panel/regularizations/<int:regularization_id>/<str:new_status>/',
        update_regularization_status,
        name='admin-regularization-status',
    ),
    path('checkin/', CheckInView.as_view(), name='checkin'),
    path('checkout/', CheckOutView.as_view(), name='checkout'),
    path('dashboard/', UserDashboardView.as_view(), name='dashboard'),
    path('attendance-report/', AttendanceReportView.as_view(), name='attendance-report'),
    path(
        'attendance-regularizations/',
        EmployeeAttendanceRegularizationView.as_view(),
        name='attendance-regularizations',
    ),
    path('employee/tasks/', EmployeeTasksView.as_view(), name='employee-tasks'),
    path('employee/directory/', EmployeeDirectoryView.as_view(), name='employee-directory'),
    path('employee/leaves/', EmployeeLeaveRequestsView.as_view(), name='employee-leaves'),
    path('employee/salary/', EmployeeSalaryView.as_view(), name='employee-salary'),
    path('employee/salary/payslip/', EmployeePayslipPdfView.as_view(), name='employee-payslip-pdf'),
    path('employee/helpdesk/', EmployeeHelpdeskTicketsView.as_view(), name='employee-helpdesk'),
    path('me/', MeView.as_view(), name='me'),
    path('admin/stats/', AdminDashboardStatsView.as_view(), name='admin-stats'),
    path('admin/dashboard/', AdminDashboardView.as_view(), name='admin-dashboard'),
    path('admin/employees/', AdminEmployeesApiView.as_view(), name='admin-employees'),
    path('admin/employees/<int:employee_id>/', AdminEmployeeDetailApiView.as_view(), name='admin-employee-detail'),
    path(
        'admin/employees/<int:employee_id>/location/',
        AdminEmployeeLocationApiView.as_view(),
        name='admin-employee-location',
    ),
    path('admin/attendance/', AdminAttendanceApiView.as_view(), name='admin-attendance'),
    path('admin/tasks/', AdminTasksApiView.as_view(), name='admin-tasks'),
    path('admin/leaves/<int:leave_id>/status/', AdminLeaveStatusApiView.as_view(), name='admin-leave-status-api'),
    path(
        'admin/regularizations/<int:regularization_id>/status/',
        AdminRegularizationStatusApiView.as_view(),
        name='admin-regularization-status-api',
    ),
    path('admin/helpdesk/<int:ticket_id>/status/', AdminHelpdeskStatusApiView.as_view(), name='admin-helpdesk-status-api'),
    path('password-reset/request/', PasswordResetRequestView.as_view(), name='password-reset-request'),
    path('password-reset/verify/', PasswordResetVerifyView.as_view(), name='password-reset-verify'),
    path('password-reset/confirm/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
]
