from django.urls import path

from .career_views import (
    EmployeeDocumentsView,
    EmployeeExitRequestsView,
    EmployeeJobOpeningsView,
    EmployeeLeaveTypesView,
    PublicJobApplyView,
    PublicJobOpeningDetailView,
    PublicJobOpeningListView,
)
from .views import (
    AdminAttendanceApiView,
    AdminAttendanceSettingsApiView,
    AdminDashboardStatsView,
    AdminDashboardView,
    AdminEmployeeDetailApiView,
    AdminEmployeeLocationApiView,
    AdminEmployeesApiView,
    AdminHelpdeskStatusApiView,
    AdminReimbursementRequestsView,
    AdminSalaryRecordsView,
    AdminLeaveStatusApiView,
    AdminTasksApiView,
    AdminRegularizationStatusApiView,
    AttendanceReportView,
    CheckInView,
    CheckOutView,
    EmployeeAttendanceRegularizationView,
    EmployeeDirectoryView,
    EmployeeHelpdeskTicketsView,
    EmployeeLeaveRequestsView,
    EmployeePayslipPdfView,
    EmployeeReimbursementRequestsView,
    EmployeeSalaryView,
    EmployeeTasksView,
    MeView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    PasswordResetVerifyView,
    UserDashboardView,
    admin_dashboard_panel,
    update_leave_request_status,
    update_regularization_status,
)
from .hr_views import (
    HrAdminLeaveDetailView,
    HrAdminLeaveListCreateView,
    HrCandidateDetailView,
    HrCandidateListCreateView,
    HrDepartmentDetailView,
    HrDepartmentListCreateView,
    HrDesignationDetailView,
    HrDesignationListCreateView,
    HrEmployeeDocumentDetailView,
    HrEmployeeDocumentListCreateView,
    HrExitRequestDetailView,
    HrExitRequestListCreateView,
    HrJobOpeningDetailView,
    HrJobOpeningListCreateView,
    HrLeaveTypeDetailView,
    HrLeaveTypeListCreateView,
    HrPerformanceReviewDetailView,
    HrPerformanceReviewListCreateView,
    HrReportsSummaryView,
    HrShiftAssignmentDetailView,
    HrShiftAssignmentListCreateView,
    HrShiftDetailView,
    HrShiftListCreateView,
)


urlpatterns = [
    path('admin-panel/', admin_dashboard_panel, name='admin-dashboard-panel'),
    path(
        'admin-panel/leaves/<int:leave_id>/<str:new_status>/',
        update_leave_request_status,
        name='admin-leave-status',
    ),
    path(
        'admin-panel/regularizations/<int:regularization_id>/<str:new_status>/',
        update_regularization_status,
        name='admin-regularization-status',
    ),
    path('checkin/', CheckInView.as_view(), name='checkin'),
    path('checkout/', CheckOutView.as_view(), name='checkout'),
    path('dashboard/', UserDashboardView.as_view(), name='dashboard'),
    path('attendance-report/', AttendanceReportView.as_view(), name='attendance-report'),
    path(
        'attendance-regularizations/',
        EmployeeAttendanceRegularizationView.as_view(),
        name='attendance-regularizations',
    ),
    path('employee/tasks/', EmployeeTasksView.as_view(), name='employee-tasks'),
    path('employee/directory/', EmployeeDirectoryView.as_view(), name='employee-directory'),
    path('employee/leaves/', EmployeeLeaveRequestsView.as_view(), name='employee-leaves'),
    path('employee/leave-types/', EmployeeLeaveTypesView.as_view(), name='employee-leave-types'),
    path('employee/jobs/', EmployeeJobOpeningsView.as_view(), name='employee-jobs'),
    path('employee/exit-requests/', EmployeeExitRequestsView.as_view(), name='employee-exit-requests'),
    path('employee/documents/', EmployeeDocumentsView.as_view(), name='employee-documents'),
    path('public/jobs/', PublicJobOpeningListView.as_view(), name='public-jobs'),
    path('public/jobs/<slug:slug>/', PublicJobOpeningDetailView.as_view(), name='public-job-detail'),
    path('public/jobs/<slug:slug>/apply/', PublicJobApplyView.as_view(), name='public-job-apply'),
    path('employee/salary/', EmployeeSalaryView.as_view(), name='employee-salary'),
    path('employee/reimbursements/', EmployeeReimbursementRequestsView.as_view(), name='employee-reimbursements'),
    path('employee/salary/payslip/', EmployeePayslipPdfView.as_view(), name='employee-payslip-pdf'),
    path('employee/helpdesk/', EmployeeHelpdeskTicketsView.as_view(), name='employee-helpdesk'),
    path('me/', MeView.as_view(), name='me'),
    path('admin/stats/', AdminDashboardStatsView.as_view(), name='admin-stats'),
    path('admin/dashboard/', AdminDashboardView.as_view(), name='admin-dashboard'),
    path('admin/employees/', AdminEmployeesApiView.as_view(), name='admin-employees'),
    path('admin/employees/<int:employee_id>/', AdminEmployeeDetailApiView.as_view(), name='admin-employee-detail'),
    path(
        'admin/employees/<int:employee_id>/location/',
        AdminEmployeeLocationApiView.as_view(),
        name='admin-employee-location',
    ),
    path('admin/attendance/', AdminAttendanceApiView.as_view(), name='admin-attendance'),
    path('admin/attendance-settings/', AdminAttendanceSettingsApiView.as_view(), name='admin-attendance-settings'),
    path('admin/reimbursements/', AdminReimbursementRequestsView.as_view(), name='admin-reimbursements'),
    path('admin/salary-records/', AdminSalaryRecordsView.as_view(), name='admin-salary-records'),
    path('admin/tasks/', AdminTasksApiView.as_view(), name='admin-tasks'),
    path('admin/leaves/<int:leave_id>/status/', AdminLeaveStatusApiView.as_view(), name='admin-leave-status-api'),
    path(
        'admin/regularizations/<int:regularization_id>/status/',
        AdminRegularizationStatusApiView.as_view(),
        name='admin-regularization-status-api',
    ),
    path('admin/helpdesk/<int:ticket_id>/status/', AdminHelpdeskStatusApiView.as_view(), name='admin-helpdesk-status-api'),
    path('admin/hr/departments/', HrDepartmentListCreateView.as_view(), name='hr-departments'),
    path('admin/hr/departments/<int:pk>/', HrDepartmentDetailView.as_view(), name='hr-department-detail'),
    path('admin/hr/designations/', HrDesignationListCreateView.as_view(), name='hr-designations'),
    path('admin/hr/designations/<int:pk>/', HrDesignationDetailView.as_view(), name='hr-designation-detail'),
    path('admin/hr/shifts/', HrShiftListCreateView.as_view(), name='hr-shifts'),
    path('admin/hr/shifts/<int:pk>/', HrShiftDetailView.as_view(), name='hr-shift-detail'),
    path('admin/hr/shift-assignments/', HrShiftAssignmentListCreateView.as_view(), name='hr-shift-assignments'),
    path('admin/hr/shift-assignments/<int:pk>/', HrShiftAssignmentDetailView.as_view(), name='hr-shift-assignment-detail'),
    path('admin/hr/leave-types/', HrLeaveTypeListCreateView.as_view(), name='hr-leave-types'),
    path('admin/hr/leave-types/<int:pk>/', HrLeaveTypeDetailView.as_view(), name='hr-leave-type-detail'),
    path('admin/hr/leaves/', HrAdminLeaveListCreateView.as_view(), name='hr-admin-leaves'),
    path('admin/hr/leaves/<int:pk>/', HrAdminLeaveDetailView.as_view(), name='hr-admin-leave-detail'),
    path('admin/hr/job-openings/', HrJobOpeningListCreateView.as_view(), name='hr-job-openings'),
    path('admin/hr/job-openings/<int:pk>/', HrJobOpeningDetailView.as_view(), name='hr-job-opening-detail'),
    path('admin/hr/candidates/', HrCandidateListCreateView.as_view(), name='hr-candidates'),
    path('admin/hr/candidates/<int:pk>/', HrCandidateDetailView.as_view(), name='hr-candidate-detail'),
    path('admin/hr/exit-requests/', HrExitRequestListCreateView.as_view(), name='hr-exit-requests'),
    path('admin/hr/exit-requests/<int:pk>/', HrExitRequestDetailView.as_view(), name='hr-exit-request-detail'),
    path('admin/hr/documents/', HrEmployeeDocumentListCreateView.as_view(), name='hr-documents'),
    path('admin/hr/documents/<int:pk>/', HrEmployeeDocumentDetailView.as_view(), name='hr-document-detail'),
    path('admin/hr/performance-reviews/', HrPerformanceReviewListCreateView.as_view(), name='hr-performance-reviews'),
    path('admin/hr/performance-reviews/<int:pk>/', HrPerformanceReviewDetailView.as_view(), name='hr-performance-review-detail'),
    path('admin/hr/reports/summary/', HrReportsSummaryView.as_view(), name='hr-reports-summary'),
    path('password-reset/request/', PasswordResetRequestView.as_view(), name='password-reset-request'),
    path('password-reset/verify/', PasswordResetVerifyView.as_view(), name='password-reset-verify'),
    path('password-reset/confirm/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
]
